# Generated by Django 4.2.13 on 2024-06-07 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecommendedClothes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top', models.ImageField(upload_to='user_pictures')),
                ('bottom', models.ImageField(upload_to='user_pictures')),
                ('outer', models.ImageField(upload_to='user_pictures')),
            ],
        ),
        migrations.DeleteModel(
            name='recommend',
        ),
    ]
