# Generated by Django 4.2.13 on 2024-06-07 18:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommend', '0002_recommendedclothes_delete_recommend'),
    ]

    operations = [
        migrations.AddField(
            model_name='recommendedclothes',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AlterField(
            model_name='recommendedclothes',
            name='bottom',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='recommendedclothes',
            name='outer',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='recommendedclothes',
            name='top',
            field=models.CharField(max_length=100),
        ),
    ]
