# Generated by Django 4.2.7 on 2024-06-01 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0004_event_clothes_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='clothes_data',
        ),
        migrations.AddField(
            model_name='event',
            name='bottom_clothes',
            field=models.ImageField(blank=True, null=True, upload_to='clothes/'),
        ),
        migrations.AddField(
            model_name='event',
            name='outer_clothes',
            field=models.ImageField(blank=True, null=True, upload_to='clothes/'),
        ),
        migrations.AddField(
            model_name='event',
            name='top_clothes',
            field=models.ImageField(blank=True, null=True, upload_to='clothes/'),
        ),
    ]
