# Generated by Django 4.2.7 on 2024-06-01 19:36

import cal.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0005_remove_event_clothes_data_event_bottom_clothes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='bottom_clothes',
            field=models.ImageField(blank=True, null=True, upload_to=cal.models.get_upload_to),
        ),
        migrations.AlterField(
            model_name='event',
            name='outer_clothes',
            field=models.ImageField(blank=True, null=True, upload_to=cal.models.get_upload_to),
        ),
        migrations.AlterField(
            model_name='event',
            name='top_clothes',
            field=models.ImageField(blank=True, null=True, upload_to=cal.models.get_upload_to),
        ),
    ]
