# Generated by Django 4.2.7 on 2024-06-03 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0007_event_image_editable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
