# Generated by Django 4.2.7 on 2024-06-01 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cal', '0003_alter_event_description_alter_event_end_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='clothes_data',
            field=models.TextField(blank=True, null=True),
        ),
    ]
