# Generated by Django 5.0.6 on 2024-05-25 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fos_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='customuser',
            table='user_data',
        ),
    ]
