# Generated by Django 5.0.6 on 2024-06-03 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserPicture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('picture', models.ImageField(upload_to='user_pictures/')),
                ('upload_date', models.DateTimeField(auto_now_add=True)),
                ('picture_name', models.CharField(blank=True, max_length=255)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.userdata')),
            ],
            options={
                'db_table': 'user_picture',
                'managed': True,
            },
        ),
    ]
